# Generated by Django 3.2.3 on 2021-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creators',
            field=models.JSONField(default=list),
        ),
    ]
