# Generated by Django 3.2.3 on 2021-05-14 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('journal', '0002_alter_article_creators'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalArticleCollection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='JournalPage',
            new_name='Journal',
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='JournalArticle',
        ),
    ]
