# Generated by Django 3.2.3 on 2021-05-14 11:32

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
