# Generated by Django 3.2.3 on 2021-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='tagline',
            field=models.TextField(blank=True),
        ),
    ]
