import secrets

from django.db.models import JSONField
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.core.models import Page

from cottage_hearth.journal.fields import CreatorsField


class Journal(Page):
    subpage_types = [
        'journal.JournalArticleCollection',
    ]

    def get_context(self, request, *args, **kwargs):
        return {
            **super().get_context(request, *args, **kwargs),
            'recent_articles': JournalArticle.objects.live().order_by('-first_published_at')[:10],
        }


class JournalArticleCollection(Page):
    subpage_types = [
        'journal.JournalArticle',
    ]


class JournalArticle(Page):
    creators = CreatorsField(default=list)

    content_panels = [
        FieldPanel('title'),
        FieldPanel('creators'),
    ]

    subpage_types = []

    def _get_autogenerated_slug(self, base_slug):
        return secrets.token_hex(8)